# Generated by Django 4.1 on 2022-08-13 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("sale_date", models.DateTimeField()),
                ("saler_name", models.CharField(max_length=50)),
                ("saler_email", models.EmailField(max_length=254)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_confirmed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ShoppingCartProductUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField()),
                (
                    "product_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="products.productunit",
                    ),
                ),
                (
                    "shopping_cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopping_cart.shoppingcart",
                    ),
                ),
            ],
        ),
    ]
