# Generated by Django 4.1 on 2022-08-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingcart",
            name="is_discarded",
            field=models.BooleanField(default=False),
        ),
    ]
