# Generated by Django 4.1 on 2022-08-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_cart", "0002_shoppingcart_is_discarded"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shoppingcart",
            old_name="saler_email",
            new_name="buyer_email",
        ),
        migrations.RenameField(
            model_name="shoppingcart",
            old_name="saler_name",
            new_name="buyer_name",
        ),
        migrations.RenameField(
            model_name="shoppingcart",
            old_name="sale_date",
            new_name="close_date",
        ),
    ]
