# Generated by Django 4.1 on 2022-08-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_cart", "0003_rename_saler_email_shoppingcart_buyer_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="shoppingcart", name="is_confirmed",),
        migrations.RemoveField(model_name="shoppingcart", name="is_discarded",),
        migrations.AddField(
            model_name="shoppingcart",
            name="status",
            field=models.CharField(
                choices=[("OE", "Oppened"), ("CF", "Confirmed"), ("DC", "Discarded")],
                default="OE",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="buyer_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="buyer_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="close_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
