# Generated by Django 4.1 on 2022-08-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_inventroyproductunitstorage_id_and_more"),
        ("shopping_cart", "0004_remove_shoppingcart_is_confirmed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingcart",
            name="shopping_cart_product_units",
            field=models.ManyToManyField(
                related_name="shoping_cart",
                through="shopping_cart.ShoppingCartProductUnit",
                to="products.productunit",
            ),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="buyer_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="buyer_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="close_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
