# Generated by Django 4.1 on 2022-08-15 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_inventroyproductunitstorage_product_unit"),
        ("shopping_cart", "0005_shoppingcart_shopping_cart_product_units_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingCartProductUnitItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField()),
                (
                    "product_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="products.productunit",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="shopping_cart_product_units",
            field=models.ManyToManyField(
                related_name="shoping_carts",
                through="shopping_cart.ShoppingCartProductUnitItem",
                to="products.productunit",
            ),
        ),
        migrations.DeleteModel(
            name="ShoppingCartProductUnit",
        ),
        migrations.AddField(
            model_name="shoppingcartproductunititem",
            name="shopping_cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shopping_cart_product_unit_items",
                to="shopping_cart.shoppingcart",
            ),
        ),
    ]
