# Generated by Django 4.1 on 2022-08-13 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_image_inventroyproductunitstorage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productunit",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_units",
                to="products.product",
            ),
        ),
    ]
