# Generated by Django 4.1 on 2022-08-15 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_productunit_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventroyproductunitstorage",
            name="id",
        ),
        migrations.AlterField(
            model_name="inventroyproductunitstorage",
            name="product_unit",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="products.productunit",
            ),
        ),
    ]
