# Generated by Django 4.1 on 2022-08-23 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_rename_describtion_product_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryProductUnitStorage",
            fields=[
                (
                    "product_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="inventory_product_unit_storage",
                        serialize=False,
                        to="products.productunit",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="InventroyProductUnitStorage",
        ),
    ]
